import * as CONSTANTS from './constants';

export const keyNames = [
  CONSTANTS.C,
  CONSTANTS.C_SHARP,
  CONSTANTS.D,
  CONSTANTS.D_SHARP,
  CONSTANTS.E,
  CONSTANTS.F,
  CONSTANTS.F_SHARP,
  CONSTANTS.G,
  CONSTANTS.G_SHARP,
  CONSTANTS.A,
  CONSTANTS.A_SHARP,
  CONSTANTS.B,
];
